#!/bin/bash

DOCKER_COMPOSE_FILE_NAME="docker-compose.yml"

GRAFANA_FOLDER="grafana"
METRICS_FOLDER="metrics"
PROMETHEUS_FOLDER="prometheus"

# Dashboarding
DASBOARDING_FOLDER="dashboarding"

# Metrics
export PROMETHEUS="$METRICS_FOLDER/$PROMETHEUS_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

export GRAFANA="$DASBOARDING_FOLDER/$GRAFANA_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

export ALL_COMPOSE_FILES=" -f "$GRAFANA\
" -f "$PROMETHEUS\
