#!/bin/bash

DOCKER_COMPOSE_FILE_NAME="docker-compose.yml"

# Dashboarding
DASBOARDING_FOLDER="dashboarding"
GRAFANA_FOLDER="grafana"
export GRAFANA="$DASBOARDING_FOLDER/$GRAFANA_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

# Metrics
METRICS_FOLDER="metrics"
PROMETHEUS_FOLDER="prometheus"
export PROMETHEUS="$METRICS_FOLDER/$PROMETHEUS_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

# Tracing
METRICS_FOLDER="tracing"
ZIPKIN_FOLDER="zipkin"
export ZIPKIN="$METRICS_FOLDER/$ZIPKIN_FOLDER/$DOCKER_COMPOSE_FILE_NAME"
JAEGER_FOLDER="jaeger"
export JAEGER="$METRICS_FOLDER/$JAEGER_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

# Logs
LOGS_FOLDER="logs"
ELK_FOLDER="elk"
export ELK="$LOGS_FOLDER/$ELK_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

# Self Monitoring
SELF_MONITORING_FOLDER="self-monitoring"
SELF_METRICS_FOLDER="metrics"
export SELF_METRICS="$SELF_MONITORING_FOLDER/$SELF_METRICS_FOLDER/$DOCKER_COMPOSE_FILE_NAME"

export ALL_COMPOSE_FILES=" -f "$GRAFANA\
" -f "$PROMETHEUS\
" -f "$ZIPKIN\
" -f "$JAEGER\
" -f "$SELF_METRICS
