version: '3.8'

services:
  # Prometheus Server
  prometheus-server:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusserver_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"
volumes:
  prometheusserver_data: {}

networks:
  observabilitysandbox:
    name: observabilitysandbox
    external: true
