version: '3.8'

services:
  # Node exporter
  node-exporter:
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  # CAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.40.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    ports:
      - 8010:8080
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

networks:
  observabilitysandbox:    
    name: observabilitysandbox
    external: true
