{
 "title": "HTTP Metrics (Micrometer)",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).\nThis is a fork of dashboard 6756, fixed for Spring Boot 2.3 and support for Jetty instead of Tomcat along with scraping endpoints' metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", status!=\"200\"}[$__interval])) / sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", status!=\"200\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Req / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
    }
   ]
  },
  { "title": "Http Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) / sum(irate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.5\"})"
    }
   ]
  },
  {
   "title": "p90",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.9\"})"
    }
   ]
  },
  {
   "title": "p95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.95\"})"
    }
   ]
  },
  {
   "title": "p99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"})"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top 10 Most Used Endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri!~\".*actuator.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Http Client Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m])) / sum(rate(http_client_requests_seconds_count{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}[1m]))"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_max{application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"})"
    }
   ]
  }
 ]
}