# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: 'cluster01'
    replica: 'r1'

scrape_configs:
  # Prometheus self monitoring
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - prometheus-server:9090

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  # Spring petclinic services monitoring
  # You can use Eureka's application instance metadata.
  # If you are using SpringBoot, you can add metadata using eureka.instance.metadataMap like this:
  # application.yaml (spring-boot)
  # eureka:
  #  instance:
  #    metadataMap:
  #      "prometheus.scrape": "true"
  #      "prometheus.path": "/actuator/prometheus"
  - job_name: eureka-discovery
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    eureka_sd_configs:
    - server: http://discovery-server:8761/eureka
      refresh_interval: 30s
    relabel_configs:
    # Relabel to customize metric path based on application
    # "prometheus.path = <metric path>" annotation.
    - source_labels: [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    # Relabel to scrape only application that have
    # "prometheus.scrape = true" metadata.
    - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
      action: keep
      regex: true

  #- job_name: api-gateway
  #  metrics_path: /actuator/prometheus
  #  static_configs:
  #  - targets: ['api-gateway:8080']

  #- job_name: customers-service
  #  metrics_path: /actuator/prometheus
  #  static_configs:
  #  - targets: ['customers-service:8081']

  #- job_name: visits-service
  #  metrics_path: /actuator/prometheus
  #  static_configs:
  #  - targets: ['visits-service:8082']

  #- job_name: vets-service
  #  metrics_path: /actuator/prometheus
  #  static_configs:
  #  - targets: ['vets-service:8083']
